title: Christina Zheng
theme: minima
description: v0.7 Â· Blog about healthcare, data, and startups

permalink: /:title/

header_pages:
  - writing.md
  - about.md
  - projects.md

minima:
  skin: solarized-light
