title: Leyin Zheng
description: Minimalist notes on work and learning
url: "https://leyinzheng.com"

markdown: kramdown
permalink: /writing/:title/

theme: null

plugins:
  - jekyll-seo-tag

description: Writing about healthcare, data, and startups

header_pages:
  - writing.md
  - about.md
  - projects.md
